import type { MLFeatures } from "../types"

export function featuresToArray(features: MLFeatures): number[] {
  return [
    features.hasTimeoutTerms ? 1.0 : 0.0,
    features.hasDatabaseTerms ? 1.0 : 0.0,
    features.hasAuthTerms ? 1.0 : 0.0,
    features.hasRuntimeErrorTerms ? 1.0 : 0.0,
    features.hasValidationTerms ? 1.0 : 0.0,
    features.isProduction ? 1.0 : 0.0,
    features.hasCriticalRoute ? 1.0 : 0.0,
    features.hasIntegrationTerms ? 1.0 : 0.0,
    features.hasInfraTerms ? 1.0 : 0.0,
    features.isHandled ? 1.0 : 0.0,
    features.hasNodeRuntime ? 1.0 : 0.0,
    features.isTypeError ? 1.0 : 0.0,
    features.isRangeError ? 1.0 : 0.0,
    features.isSyntaxError ? 1.0 : 0.0,
    features.isReferenceError ? 1.0 : 0.0,
    features.isNativeError ? 1.0 : 0.0,
    features.isCustomError ? 1.0 : 0.0,
    features.hasECONNREFUSED ? 1.0 : 0.0,
    features.hasECONNRESET ? 1.0 : 0.0,
    features.hasENOTFOUND ? 1.0 : 0.0,
    features.hasEACCES ? 1.0 : 0.0,
    features.hasENOENT ? 1.0 : 0.0,
    features.hasHTTPStatus4xx ? 1.0 : 0.0,
    features.hasHTTPStatus5xx ? 1.0 : 0.0,
    features.hasNodeErrorCode ? 1.0 : 0.0,
    features.stackDepth,
    features.appFrameCount,
    features.appFrameRatio,
    features.topFrameIsVendor ? 1.0 : 0.0,
    features.hasORMInStack ? 1.0 : 0.0,
    features.hasDBDriverInStack ? 1.0 : 0.0,
    features.hasHTTPClientInStack ? 1.0 : 0.0,
    features.hasQueueInStack ? 1.0 : 0.0,
    features.hasAuthLibInStack ? 1.0 : 0.0,
    features.hasFrameworkInStack ? 1.0 : 0.0,
    features.hasValidatorInStack ? 1.0 : 0.0,
    features.hasMiddlewarePattern ? 1.0 : 0.0,
    features.hasControllerPattern ? 1.0 : 0.0,
    features.hasServicePattern ? 1.0 : 0.0,
    features.hasRepositoryPattern ? 1.0 : 0.0,
    features.hasResolverPattern ? 1.0 : 0.0,
    features.hasGuardPattern ? 1.0 : 0.0,
    features.hasInterceptorPattern ? 1.0 : 0.0,
    features.isGET ? 1.0 : 0.0,
    features.isPOST ? 1.0 : 0.0,
    features.isPUTorPATCH ? 1.0 : 0.0,
    features.isDELETE ? 1.0 : 0.0,
    features.isAPIRoute ? 1.0 : 0.0,
    features.routeSegmentCount,
    features.breadcrumbCount,
    features.hasHTTPBreadcrumbs ? 1.0 : 0.0,
    features.hasDBQueryBreadcrumbs ? 1.0 : 0.0,
    features.lastBreadcrumbIs4xx ? 1.0 : 0.0,
    features.lastBreadcrumbIs5xx ? 1.0 : 0.0,
    features.isStaging ? 1.0 : 0.0,
    features.isServerOS ? 1.0 : 0.0,
    features.isLambda ? 1.0 : 0.0,
    features.isDocker ? 1.0 : 0.0,
    features.isKubernetes ? 1.0 : 0.0,
    features.hasCloudProvider ? 1.0 : 0.0,
    features.titleWordCount,
    features.titleHasColon ? 1.0 : 0.0,
    features.hasStackTrace ? 1.0 : 0.0,
    features.errorMessageLength
  ]
}
